# Generated by Django 5.0.2 on 2024-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_painting_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
